api_hash: 2d3673e18b462f8032c4eea2f50b9f52
api_id: 7712824
chat_id: -1001701936331
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
